### ISSUE TITLE
server.go can't be build

### ISSUE THREAD

**Issue by Blogoslov** [prevoty/rpc_tutorial#1]
Hello. 
During building server.go program I see following output:

./server.go:15: undefined: NewRPC

This function NewRPC is in rpc.go file - but how it will become available if it missing as import at server.go file? Is it a issue?

Regards.

**Comment by ahamilton55** [comment]
Hi,

What command are you using to build? I simply used "go build" inside the repository and it worked fine for me.

**Comment by Blogoslov** [comment]
Hi,
I used "go build server.go" command.
Will try the same command but without file name substitution.

**Comment by Ricky54326** [comment]
Same issue here. Ideas? 

```shell
» go build server.go                                                        2 ↵
./server.go:15: undefined: NewRPC
```

**Comment by Pursuit92** [comment]
As @ahamilton55 said, you just have to run `go build` in the rpc_tutorial directory. When you try to `go build server.go`, you're only compiling one file which doesn't have everything defined.
